# Generated by Django 2.0.13 on 2020-05-15 19:45

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('creater_id', models.IntegerField(default=0, verbose_name='创建人ID')),
                ('updater_id', models.IntegerField(default=0, verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '系统用户表',
                'verbose_name_plural': '系统用户表',
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('guid', models.CharField(blank=True, max_length=50, verbose_name='全局唯一标识')),
                ('name', models.CharField(max_length=200, verbose_name='视频名称')),
                ('desc', models.CharField(blank=True, max_length=500, verbose_name='视频描述')),
                ('artists', models.CharField(default='', max_length=200, verbose_name='演员')),
                ('release_time', models.DateTimeField(null=True, verbose_name='上映时间')),
                ('res_url', models.CharField(max_length=300, verbose_name='视频地址')),
                ('thumbnail_url', models.CharField(max_length=300, verbose_name='缩略图')),
                ('cover_url', models.CharField(max_length=300, verbose_name='封面图')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('creater_id', models.IntegerField(verbose_name='创建人ID')),
                ('creater_name', models.CharField(max_length=10, verbose_name='创建人姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '视频表单',
                'verbose_name_plural': '视频表单',
                'db_table': 'tb_base_video',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='分类描述')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('creater_id', models.IntegerField(verbose_name='创建人ID')),
                ('creater_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='评分')),
                ('creater_id', models.IntegerField(verbose_name='创建人ID')),
                ('creater_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.BaseVideo', verbose_name='视频')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'tb_comment',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=20, verbose_name='变量key')),
                ('value', models.CharField(max_length=20, verbose_name='变量value')),
            ],
            options={
                'verbose_name': '网站配置表',
                'verbose_name_plural': '网站配置表',
                'db_table': 'tb_config',
            },
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('creater_id', models.IntegerField(verbose_name='创建人ID')),
                ('creater_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '发现表',
                'verbose_name_plural': '发现表',
                'db_table': 'tb_discover',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, verbose_name='key')),
                ('created', models.DateTimeField(verbose_name='创建时间')),
                ('user_id', models.IntegerField(unique=True, verbose_name='创建人ID')),
            ],
            options={
                'verbose_name': 'refresh token表',
                'verbose_name_plural': 'refresh token表',
                'db_table': 'tb_refresh_token',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('creater_id', models.IntegerField(verbose_name='创建人ID')),
                ('creater_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '系统角色表',
                'verbose_name_plural': '系统角色表',
                'db_table': 'tb_sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
            ],
            options={
                'verbose_name': '用户角色关联表',
                'verbose_name_plural': '用户角色关联表',
                'db_table': 'tb_sys_user_role',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='标签描述')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('creater_id', models.IntegerField(verbose_name='创建人ID')),
                ('creater_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'tb_tags',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.IntegerField(default=0, verbose_name='用户ID')),
                ('vid', models.IntegerField(default=0, verbose_name='视频ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('action', models.CharField(max_length=40, verbose_name='访问路径')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '用户轨迹表',
                'verbose_name_plural': '用户轨迹表',
                'db_table': 'tb_travel',
            },
        ),
        migrations.AddField(
            model_name='basevideo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Category', verbose_name='视频类别'),
        ),
        migrations.AddField(
            model_name='basevideo',
            name='tags',
            field=models.ManyToManyField(default=1, to='backend.Tags', verbose_name='视频标签'),
        ),
    ]
